- hosts: localhost
  vars:
    production_vault_url: https://kvault.bhdgsystematic.com
    production_vault_cacert: /etc/ssl/certs/ca-certificates.crt
  tasks:
    - name: CERT login to vault
      jr200.vault.login:
        vault_addr: "{{ production_vault_url }}"
        vault_cacert: "{{ production_vault_cacert }}"
        method: cert
        cert_key_file: /Users/jraghunandan/mycode/ansible-vault-collection/local/test.key
        cert_file: /Users/jraghunandan/mycode/ansible-vault-collection/local/test.crt
    - name: TOKEN login to vault
      jr200.vault.login:
        vault_addr: "{{ production_vault_url }}"
        vault_cacert: "{{ production_vault_cacert }}"
        secret: s.3eWjCvPK1v787A6mIITaOnis
      register: vault_credential
    - name: test TOKEN lookup_self
      jr200.vault.lookup_self:
        vault_addr: "{{ production_vault_url }}"
        vault_cacert: "{{ production_vault_cacert }}"
    - name: USERPASS login to vault
      jr200.vault.login:
        method: userpass
        username: test
    - name: test USERPASS lookup_self
      jr200.vault.lookup_self:
        vault_addr: "{{ production_vault_url }}"
        vault_cacert: "{{ production_vault_cacert }}"
    - name: cached USERPASS login to vault
      jr200.vault.login:
        method: userpass
        username: test
    - name: LDAP login to vault
      jr200.vault.login:
        vault_addr: "{{ production_vault_url }}"
        vault_cacert: "{{ production_vault_cacert }}"
        method: ldap
    - name: get secret
      jr200.vault.kv:
        vault_addr: "{{ production_vault_url }}"
        vault_cacert: "{{ production_vault_cacert }}"
        secret_path: test
        secret_version: 1
        client_token: "{{ vault_credential.client_token }}"
      register: kv_result
    - name: print secret
      debug:
        var: kv_result
